// <auto-generated />
using System;
using Keyos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Keyos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190216175741_stocksTableAdded")]
    partial class stocksTableAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Keyos.Models.Stock", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Symbol");

                    b.Property<int>("change");

                    b.Property<int>("changeOverTime");

                    b.Property<int>("changePercent");

                    b.Property<int>("close");

                    b.Property<string>("date");

                    b.Property<int>("high");

                    b.Property<string>("label");

                    b.Property<int>("low");

                    b.Property<int>("open");

                    b.Property<int>("unadjustedVolume");

                    b.Property<int>("vwap");

                    b.HasKey("ID");

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("Keyos.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
