// <auto-generated />
using Keyos.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Keyos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190302030020_moveToSqlServer")]
    partial class moveToSqlServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Keyos.Models.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Symbol");

                    b.Property<int>("change");

                    b.Property<int>("changeOverTime");

                    b.Property<int>("changePercent");

                    b.Property<int>("close");

                    b.Property<string>("date");

                    b.Property<int>("high");

                    b.Property<string>("label");

                    b.Property<int>("low");

                    b.Property<int>("open");

                    b.Property<int>("unadjustedVolume");

                    b.Property<int>("volume");

                    b.Property<int>("vwap");

                    b.HasKey("ID");

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("Keyos.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
