import { Injectable } from '@angular/core';
import {merge, Observable, of as observableOf} from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import {StockSummary,Quote} from '../models/StockSummary';
import { map } from 'rxjs/operators';

const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type': 'application/json'
  })
}

@Injectable({
  providedIn: 'root'
})
export class StocksummaryService {
  quote:Quote[] = [];

  constructor(private http:HttpClient) { }

  getStocks():Observable<Quote[]> {
    return this.http.get<Quote>("https://api.iextrading.com/1.0/stock/market/batch?symbols=AABA,AAPL,ABBV,ADBE,AMAT,AMD,AMGN,AMZN,AVGO,BA,BABA,BAC,BIDU,BRK-B,C,CAT,CELG,CMCSA,CRM,CSCO,CVS,CVX,DIA,DIS,DWDP,EEM,EFA,EWJ,EWZ,FB,FXI,GDX,GE,GLD,GOOG,GOOGL,GS,HD,HYG,IBM,IEMG,INTC,IVV,IWM,IYR,JNJ,JPM,KO,LMT,LOW,LQD,LRCX,MA,MCD,MMM,MRK,MS,MSFT,MU,NFLX,NVDA,NXPI,ORCL,PFE,PG,PM,PYPL,QCOM,QQQ,SMH,SPOT,SPY,SQ,T,TLT,TQQQ,TSLA,TWTR,TXN,UNH,UNP,UTX,V,VOO,VWO,VXX,VZ,WFC,WMT,WYNN,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XOP,AABA,AAPL,ABBV,ADBE,AMAT,AMD,AMGN,AMZN,AVGO,BA,BABA,BAC,BIDU,BRK-B,C,CAT,CELG,CMCSA,CRM,CSCO,CVS,CVX,DIA,DIS,DWDP,EEM,EFA,EWJ,EWZ,FB,FXI,GDX,GE,GLD,GOOG,GOOGL,GS,HD,HYG,IBM,IEMG,INTC,IVV,IWM,IYR,JNJ,JPM,KO,LMT,LOW,LQD,LRCX,MA,MCD,MMM,MRK,MS,MSFT,MU,NFLX,NVDA,NXPI,ORCL,PFE,PG,PM,PYPL,QCOM,QQQ,SMH,SPOT,SPY,SQ,T,TLT,TQQQ,TSLA,TWTR,TXN,UNH,UNP,UTX,V,VOO,VWO,VXX,VZ,WFC,WMT,WYNN,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XOP,AABA,AAPL,ABBV,ADBE,AMAT,AMD,AMGN,AMZN,AVGO,BA,BABA,BAC,BIDU,BRK-B,C,CAT,CELG,CMCSA,CRM,CSCO,CVS,CVX,DIA,DIS,DWDP,EEM,EFA,EWJ,EWZ,FB,FXI,GDX,GE,GLD,GOOG,GOOGL,GS,HD,HYG,IBM,IEMG,INTC,IVV,IWM,IYR,JNJ,JPM,KO,LMT,LOW,LQD,LRCX,MA,MCD,MMM,MRK,MS,MSFT,MU,NFLX,NVDA,NXPI,ORCL,PFE,PG,PM,PYPL,QCOM,QQQ,SMH,SPOT,SPY,SQ,T,TLT,TQQQ,TSLA,TWTR,TXN,UNH,UNP,UTX,V,VOO,VWO,VXX,VZ,WFC,WMT,WYNN,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XOP,AABA,AAPL,ABBV,ADBE,AMAT,AMD,AMGN,AMZN,AVGO,BA,BABA,BAC,BIDU,BRK-B,C,CAT,CELG,CMCSA,CRM,CSCO,CVS,CVX,DIA,DIS,DWDP,EEM,EFA,EWJ,EWZ,FB,FXI,GDX,GE,GLD,GOOG,GOOGL,GS,HD,HYG,IBM,IEMG,INTC,IVV,IWM,IYR,JNJ,JPM,KO,LMT,LOW,LQD,LRCX,MA,MCD,MMM,MRK,MS,MSFT,MU,NFLX,NVDA,NXPI,ORCL,PFE,PG,PM,PYPL,QCOM,QQQ,SMH,SPOT,SPY,SQ,T,TLT,TQQQ,TSLA,TWTR,TXN,UNH,UNP,UTX,V,VOO,VWO,VXX,VZ,WFC,WMT,WYNN,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XOP,AABA,AAPL,ABBV,ADBE,AMAT,AMD,AMGN,AMZN,AVGO,BA,BABA,BAC,BIDU,BRK-B,C,CAT,CELG,CMCSA,CRM,CSCO,CVS,CVX,DIA,DIS,DWDP,EEM,EFA,EWJ,EWZ,FB,FXI,GDX,GE,GLD,GOOG,GOOGL,GS,HD,HYG,IBM,IEMG,INTC,IVV,IWM,IYR,JNJ,JPM,KO,LMT,LOW,LQD,LRCX,MA,MCD,MMM,MRK,MS,MSFT,MU,NFLX,NVDA,NXPI,ORCL,PFE,PG,PM,PYPL,QCOM,QQQ,SMH,SPOT,SPY,SQ,T,TLT,TQQQ,TSLA,TWTR,TXN,UNH,UNP,UTX,V,VOO,VWO,VXX,VZ,WFC,WMT,WYNN,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XOP,AABA,AAPL,ABBV,ADBE,AMAT,AMD,AMGN,AMZN,AVGO,BA,BABA,BAC,BIDU,BRK-B,C,CAT,CELG,CMCSA,CRM,CSCO,CVS,CVX,DIA,DIS,DWDP,EEM,EFA,EWJ,EWZ,FB,FXI,GDX,GE,GLD,GOOG,GOOGL,GS,HD,HYG,IBM,IEMG,INTC,IVV,IWM,IYR,JNJ,JPM,KO,LMT,LOW,LQD,LRCX,MA,MCD,MMM,MRK,MS,MSFT,MU,NFLX,NVDA,NXPI,ORCL,PFE,PG,PM,PYPL,QCOM,QQQ,SMH,SPOT,SPY,SQ,T,TLT,TQQQ,TSLA,TWTR,TXN,UNH,UNP,UTX,V,VOO,VWO,VXX,VZ,WFC,WMT,WYNN,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XOP&types=quote&displayPercent=true")
    .pipe(map(data => {
      for (var key in data) {
        if (data.hasOwnProperty(key)) {
          this.quote.push(data[key]["quote"]);
        }
      }
      return this.quote;
    }));
  }


}
